server:
  port: 8080
spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/schoolprojectmanager?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 5s
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

app:
  upload:
    base-dir: F:/school_project_manager/backend/uploads
    access-url-prefix: /uploads/
    max-file-size: 10485760
    allowed-extensions: pdf,doc,docx,xls,xlsx,ppt,pptx,zip,rar,7z,txt,md,png,jpg,jpeg,webp

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: org.example.backend.**.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha


logging:
  level:
    org.example.backend: debug

jwt:
  secret: change-this-to-a-very-long-random-secret-key
  expiration: 86400000